# 服务器配置
server:
  test_server:
    host: 192.168.22.113
    port: 22
    user: root
    password: 1
  aliyun:
    host: 39.108.99.240
    port: 18922
    user: root
    private_key: /Users/rookie/.ssh/id_rsa
project:
  back:
    sourceDir: /Volumes/Workspace/CodeRepository/qidianre-java/back
    remoteDir: /root/app
    targetName: qidianre-1.0-SNAPSHOT.jar
    deployCmd:
      before:
        - mvn clean compile package -DskipTests -Pbeta
        - cp ./target/{targetName} ./{targetName}
      after:
        - ls