# 服务器列表
[[servers]]
name = 'test_server'
host = '192.168.22.113'
port = 22
user = 'root'
password = '1'
private_key = ''
[[servers]]
name = 'aliyun'
host = '39.108.99.240'
port = 18922
user = 'root'
password = ''
private_key = '/Users/rookie/.ssh/id_rsa'

# 项目列表
[[projects]]
name = 'back'
source_dir = '/Volumes/Workspace/CodeRepository/qidianre-java/back'
remote_dir = '/root/app'
target_name = 'qidianre-1.0-SNAPSHOT.jar'
deploy_cmd.before = ['mvn clean compile package -DskipTests -Pbeta', 'cp ./target/{target_name} ./{target_name}']
deploy_cmd.after = ['ls']