# 服务器配置
server:
  test_server:
    host: 192.168.22.113
    port: 22
    user: root
    password: 1
project:
  back:
    sourceDir: /Volumes/Workspace/CodeRepository/qidianre-java/back
    remoteDir: /root/app
    targetName: qidianre-1.0-SNAPSHOT.jar
    deployCmd:
      before:
        - mvn clean compile package -DskipTests -Pbeta
        - cp ./target/{targetName} ./{targetName}
      after:
        - mv {remoteDir}/{targetName} {remoteDir}/youqu.jar
        - ps -ef|grep youqu.jar | awk '!/grep/ {print $2}' | xargs kill -9 >/dev/null 2>&1
        - nohup java -jar {remoteDir}/youqu.jar >> {remoteDir}/out.log 2>&1 &
  quartz:
    sourceDir: /Volumes/Workspace/CodeRepository/qidianre-java/quartz
    remoteDir: /root/app
    targetName: quartz-1.0-SNAPSHOT.jar
    deployCmd:
      before:
        - mvn clean compile package -DskipTests -Pbeta
        - cp ./target/{targetName} ./{targetName}
      after:
        - mv {remoteDir}/{targetName} {remoteDir}/youqu.jar
        - ps -ef|grep youqu.jar | awk '!/grep/ {print $2}' | xargs kill -9 >/dev/null 2>&1
        - nohup java -jar {remoteDir}/youqu.jar >> {remoteDir}/out.log 2>&1 &